# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    shm_size: 1g
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_NAME: postgres
    volumes:
      - ./:/database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
